### PR TITLE
Coding standards

### PR DESCRIPTION
**Pull request by SidRoberts**
It's by no means a complete coding standards overhaul - it's just an old branch I found while sorting through my old repos.

### CODE REVIEW

**Comment by sergeyklay** [comment]
Thank you

**Comment by tienanhbui** [comment]
This only work on php 7.3.
Older versions will return an error.

**Comment by SidRoberts** [comment]
What error?

**Comment by tienanhbui** [comment]
```
$roles = [
              'users'  => new Role(
                    'Users',
                    'Member privileges, granted after sign in.',
                ),
               'guests' => new Role(
                    'Guests',
                    'Anyone browsing the site who is not signed in is considered to be a "Guest".',
               )
 ];
```
Example in SecurityPlugin.php. this array throw  error like : Parse error: syntax error, unexpected ')' in C:\invo\app\plugins\SecurityPlugin.php on line 35. Because of the comma after last params  argument.

And in RegisterForm.php
```
public function initialize($entity = null, array $options = [])
{
}
```
init fuction has default type and value of param but the init put null in $option. PHP throw error  like $options  must be array!

I am using PHP 7.2 on Window.

**Comment by SidRoberts** [comment]
Proposed a fix in #75

**Pull request merged**
