### PR TITLE
Update .htaccess

### PR DESCRIPTION
**Pull request by gunarssimkuns**
RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L] gives Internal Server Error 500 when Apache VirtualDocumentRoot is used.

### CODE REVIEW

**Comment by sergeysviridenko** [comment]
I think it is unneeded in `.htaccess`

**Comment by sergeyklay** [comment]
@sergeysviridenko why?

**Comment by sergeysviridenko** [comment]
I suppose something like this can be added to apache config. Not for all.

**Comment by sergeyklay** [comment]
This is just documentation what should be done in case of problems.

**Comment by sergeyklay** [comment]
Fixed in the `0.6.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Pull request closed without merging**
