### PR TITLE
Service Container Base Class

### PR DESCRIPTION
**Pull request by tugrul**
Better way to define DI services

### CODE REVIEW

**Comment by sergeyklay** [comment]
Well, looks good to me. @andresgutierrez ?

**Comment by andresgutierrez** [comment]
We don't add changes directly to master, could you please submit this to the 2.1.x branch?

**Comment by andresgutierrez** [comment]
Could you please check the indentation in app/Services.php?

**Comment by tugrul** [comment]
@andresgutierrez I pushed as a commit

**Comment by andresgutierrez** [comment]
Thanks

**Pull request merged**
