### PR TITLE
Edit profile form, input validation & small improvements

### PR DESCRIPTION
**Pull request by aircodepl**
This time I added `ProfileForm` for edit profile view & validation for it. I also removed validation from the User model to keep things consistent. Now all validation is in dedicated forms.

The project is mostly usable right now, but I will work on this more to clean the code a bit, search for more bugs and probably improve UI a bit.

### CODE REVIEW

**Comment by aircodepl** [comment]
@niden @Jeckerson 

Hi,
Just a reminder that I added another PR request to Phalcon INVO. Taking small steps to make this app run without errors.

Wish to do more — improve UI, change bootstrap, add icons, etc. Then improve code quality & fix documentation accordingly.

Could keep maintaining it. But I need more feedback, to know that I have a green light for more... Any feedback/suggestions appreciated.

**Comment by s-ohnishi** [comment]
Hi,
I prefer to use `setVar()` for [this](https://github.com/phalcon/invo/pull/109/commits/25f2c7385083ddc43b3ad4f322187d685f4ef248).
This is because dynamic property rewriting in PHP8.2 will result in an error.
Phalcon itself will support it eventually, but I don't know when it will be.

[RegisterFrom](https://github.com/phalcon/invo/pull/109/commits/8cdfd62b040a1e7251e7958cdebb6f24ac9f1d2d)
[RegisterController](https://github.com/phalcon/invo/pull/109/commits/87225519d257513f32f03803e485a6e5d35c5c34#diff-9e2889797f10c1aecf305385c88332cdd3898288b232e470b5b10662ead58383)
I think these filters are `alnum', not `aiphanum`.
[Phalcon\Filter\Filter](https://github.com/phalcon/cphalcon/blob/master/phalcon/Filter/Filter.zep#L17)


[This ](https://github.com/phalcon/invo/pull/109/commits/87225519d257513f32f03803e485a6e5d35c5c34#diff-9e2889797f10c1aecf305385c88332cdd3898288b232e470b5b10662ead58383) uses `setDefault()` which does not exist in TagFactory.
```
$this->tag->setDefault('email', '');
$this->tag->setDefault('password', '');
```
Since it uses `$this->dispatcher->forward()`, it doesn't make sense and is unnecessary.

**Comment by s-ohnishi** [comment]
As for "[Add alias to Products ProductTypes relation](https://github.com/phalcon/invo/pull/109/commits/d6ec1e7f06f8893622e2f5c8489220fbbd9c565b)" , if you set `'alias' => 'productTypes',` instead of `'alias' => 'productType'`, I think you don't need to change searchgh.volt.

More than that, it cannot be searched correctly because it is `<form action="/products/search" role="form" method="get">` in index.volt.
It should be `<form action="/products/search" role="form" method="post">`.

**Comment by s-ohnishi** [comment]
If you use $form->isValid() in [commit](https://github.com/phalcon/invo/pull/109/commits/87225519d257513f32f03803e485a6e5d35c5c34#diff-9e2889797f10c1aecf305385c88332cdd3898288b232e470b5b10662ead58383),
I think it is good to add the following part to the form validator as well.
``` PHP
if ($password !== $repeatPassword) {
     $this->flash->error('Passwords are different');
     return;
}
```
I think it will be like below.
``` PHP
$repeatPassword->addValidators([
     new PresenceOf(['message' => 'Confirmation password is required']),
     new Confirmation(
         [
             "message" => "Passwords are different",
             "with" => "password",
         ]),
]);
```

And `isVaild()` sets the value after filtering to the second argument (entity object).
After checking the return value of `isValid()`, you can create a User instance again and supplement the missing part (and the part to be corrected) without setting the value via the filter again. .
I think it will be like below.
``` PHP
if ($this->request->isPost()) {
     $newUser = newUser();
     if ($form->isValid($this->request->getPost(), $newUser)) {
         $newUser->password = sha1($form->getFilteredValue('password'));
         $newUser->created_at = new RawValue('now()');
         $newUser->active = Status::ACTIVE;
        
         if ($newUser->save()) {
             $this->flash->success(
                 'Thanks for sign-up, please log-in to start generating invoices'
             );

             $this->dispatcher->forward([
                 'controller' => 'session',
                 'action' => 'index',
             ]);

             return;
            
         } else {
             foreach ($newUser->getMessages() as $message) {
                 $this->flash->error((string) $message);
             }
         }

     } else {
         foreach ($form->getMessages() as $message) {
             $this->flash->error((string) $message);
         }
     }

}

```

And in register/index.volt the password is "minimum 8 characters" but there is no check for that anywhere.
I think you should have added it to your form validator.

**Comment by s-ohnishi** [comment]
This [commit ](https://github.com/phalcon/invo/pull/109/commits/87225519d257513f32f03803e485a6e5d35c5c34#diff-d3febc24c14f998d3d55122d78ce40a05b82f230ac23c146e4c4f0b7d5d18398R61) says:
```PHP
if ($form->isValid($data, $user)) {
        $user->assign($data);
```
`$user` is passed to the second argument of `isValid()`, and the filtered value is set, so I don't think assign() is necessary.

**Review by Jeckerson — APPROVED** [review]

**Comment by aircodepl** [comment]
@s-ohnishi Wow! Thanks for your feedback! I was about to hire a PHP mentor just to make the code reviews of my PRs for me. :D 

I was actually trying to make the smallest changes possible and left some of the issues you mentioned purposely. Expected quicker responses/feedback and was about to make PR every day. After fixing bugs, I was about to make refactoring to better methods etc. It was a mistake because Niden/Jeckerson are busier than I thought :smile: 

Next PR will be bigger, to not leave any bugs in the code.

If you would like to cooperate on improving Phalcon example projects, we could connect through Phalcon discord (my username is `Mateusz_`).

**Comment by s-ohnishi** [comment]
Thank you for contacting me.
It seems that it has already been taken in, so I put out a supplementary [PR](https://github.com/phalcon/invo/pull/110).
I'm a github beginner, so I may be doing something wrong.
In such a case, I would appreciate it if you could understand the intention and guide me.
Also, I'm not a native English speaker, so please forgive me if my sentences and language are harsh.

**Pull request merged**
