### PR TITLE
remove malfunctions and duplicate actions

### PR DESCRIPTION
**Pull request by s-ohnishi**
I would suggest a fix for the following points:

- Even though the value is set inside `$form->isValid()`, the process of resetting it to the entity has been removed.
- Elimination of parameters containing non-serializable elements (closures)
- Fixed wrong filter name
- Correction of form method mistakes

### CODE REVIEW

**Comment by aircodepl** [comment]
Hi. I will look into it later after my work.

But for now – when making a search form, we should use the `GET` method, as we are getting/receiving data, not creating or making changes. I will suggest the fixes later.

**Comment by aircodepl** [comment]
> My modified `products/index.volt` and `companies/index.volt` are sent to the respective controller's `searchAction()` for processing. After checking with `isPost()`, it searches based on the value obtained with `getPost()`. So if the form method is not `post`, the search field you entered will not be used and everything will be listed.

I would personally keep the `GET` method and fix it on the controller side, because it's safe here, more intuitive and have the additional bonus, that I can copy the search URL.

:heavy_check_mark: - But you are right, all controllers are expecting the POST right now.

---

More importantly, what is worrying me is this unsetting of DI. These value from `$query->getParams()` should be only parameters for `find` and `findFirst`.

**Comment by s-ohnishi** [comment]
> This value from $query->getParams() should be only parameters for ::find and ::findFirst.

In that respect, I aimed only to eliminate the inclusion of elements that cannot be serialized.
I didn't think deeply about what kind of content to save because I thought that it had already been considered when v1.0 was released.
Adding `"parameters" => $parameters` to `Paginator` was just a coincidence after trying various things.
When I tried to decipher the `.zep` file, I didn't understand it well enough to know what elements should be left in what way.

**Comment by s-ohnishi** [comment]
It's been a while, are you busy?
Or is there something I should change?
I think that there is no problem for the following reasons.

> More importantly, what is worrying me is this unsetting of DI in returned value.

Isn't it the PHP specification that closures cannot be serialized?
I don't think you can remove the closure from Di, so I think the only thing you can do is remove Di from the serialized element.
It may be necessary to consider whether to do it with Phalcon or with the INVO app.
However, since modification of Phalcon itself is out of the scope of the INVO project, I am proposing this as something that can be done with the INVO app.

There may be situations where you expect the return value of $query->getParams() to contain Di, but Paginator doesn't seem to need Di in the values you give as parameters.
Therefore, as the value to be set to $this->persistent->searchParams, it seems that there is no problem in removing Di from the return value of $query->getParams().

> This value from $query->getParams() should be only parameters for ::find and ::findFirst.

$query->getParams() does not include Di in the return value of Phalcon, so you can use $query->getParams() if necessary.
Since it cannot be serialized, when using $this->persistent->searchParams, the program must assume that Di is not included.
There is no need to restore the Di at the time of serialization, and the current Di can be used, so there are various ways to obtain Di.

**Review by Jeckerson — APPROVED** [review]

**Comment by s-ohnishi** [comment]
thank you.
Now proceed to the next step.

**Pull request merged**
